---
openapi: 3.0.0
info:
  title: Test
  description: ""
  version: "1.0"
servers:
- url: http://localhost:8080/api
paths:
  /user/register:
    post:
      summary: ""
      description: register for user
      operationId: register
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponse'
      security: []
  /institute/{id}/slots:
    get:
      summary: ""
      operationId: getInstituteSlots
      parameters:
      - name: page
        in: query
        schema:
          type: integer
      - name: pageSize
        in: query
        schema:
          type: integer
      - name: query
        in: query
        schema:
          pattern: "([\\w.]+)([^']+?)('(?:.*?)'|[+-]?(?:[0-9]*[.])?[0-9]+)(?:;|$)"
          type: string
          example: username='abc';id='abc';age=18
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SlotsSearchResponse'
    delete:
      summary: ""
      description: deletes an appointment
      operationId: deleteInstituteSlot
      responses:
        "200":
          description: OK
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: string
  /user/slots:
    get:
      tags: []
      summary: Your GET endpoint
      description: get all slots of a user
      operationId: getSlots
      parameters:
      - name: page
        in: query
        schema:
          type: integer
      - name: pageSize
        in: query
        schema:
          type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SlotsSearchResponse'
      security:
      - Authorization: []
  /user:
    get:
      tags: []
      summary: Your GET endpoint
      description: get user that is active
      operationId: getUser
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      security:
      - Authorization: []
  /institute:
    get:
      tags: []
      summary: Your GET endpoint
      description: ""
      operationId: getInstitutes
      parameters:
      - name: page
        in: query
        schema:
          type: integer
      - name: pageSize
        in: query
        schema:
          type: integer
      - name: query
        in: query
        schema:
          pattern: "([\\w.]+)([^']+?)('(?:.*?)'|[+-]?(?:[0-9]*[.])?[0-9]+)(?:;|$)"
          type: string
          example: username='abc';id='abc';age=18
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstitutesSearchResponse'
    post:
      summary: ""
      description: creates an institute
      operationId: createInstitute
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Institute'
      responses:
        "200":
          description: OK
    delete:
      summary: ""
      description: ""
      operationId: deleteInstitute
      responses:
        "200":
          description: OK
      security:
      - Authorization: []
  /institute/{id}:
    get:
      tags: []
      summary: Your GET endpoint
      operationId: getInstitute
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Institute'
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: string
  /slot/{slotId}/make:
    post:
      summary: ""
      operationId: makeAppointment
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                enum:
                - SUCESSFULLY_CREATED
                - ALREADY_OCCUPIED
                - NOT_AVAILABLE
                type: string
      security:
      - Authorization: []
    parameters:
    - name: slotId
      in: path
      required: true
      schema:
        type: integer
  /slot/{slotId}/clear:
    delete:
      summary: ""
      operationId: clearSlot
      responses:
        "200":
          description: OK
    parameters:
    - name: slotId
      in: path
      required: true
      schema:
        type: string
  /slot:
    post:
      summary: ""
      operationId: createSlot
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SlotCreationRequest'
      responses:
        "200":
          description: OK
      security:
      - Authorization: []
  /institute/{id}/employees:
    post:
      summary: ""
      operationId: addEmployee
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddEmployeeRequest'
      responses:
        "200":
          description: OK
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: string
components:
  schemas:
    RegisterRequest:
      title: register
      required:
      - firstname
      - lastname
      - email
      - password
      type: object
      properties:
        firstname:
          type: string
        lastname:
          type: string
        email:
          type: string
        password:
          type: string
        phone:
          type: string
    Slot:
      title: Slot
      description: ""
      type: object
      properties:
        dateTimestamp:
          type: number
        user:
          $ref: '#/components/schemas/User'
        institute:
          $ref: '#/components/schemas/Institute'
        durationInMinutes:
          type: integer
    SlotCreationRequest:
      title: SlotCreationRequest
      required:
      - dateTimestamp
      - durationInMinutes
      type: object
      properties:
        dateTimestamp:
          type: integer
        durationInMinutes:
          type: integer
    Institute:
      title: Institute
      type: object
      properties:
        name:
          type: string
        id:
          type: string
        phone:
          type: string
        address:
          $ref: '#/components/schemas/Address'
        description:
          default: ' '
          type: string
        employees:
          type: array
          items:
            type: string
    Address:
      title: Address
      type: object
      properties:
        city:
          type: string
        street:
          type: string
        house_number:
          type: string
        latitude:
          type: string
        longitude:
          type: string
        postal_code:
          type: string
    User:
      title: User
      type: object
      properties:
        firstname:
          type: string
        lastname:
          type: string
        email:
          type: string
        phone:
          type: string
    RegisterResponse:
      title: ""
      enum:
      - SUCCESSFULLY_CREATED
      - ALREADY_EXISTS
      type: string
    InstitutesSearchResponse:
      title: InstitutesSearchResponse
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Institute'
        total:
          type: integer
    SlotsSearchResponse:
      title: SlotsSearchResponse
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Slot'
        total:
          type: integer
    AddEmployeeRequest:
      title: AddEmployeeRequest
      type: object
      properties:
        name:
          type: string
  securitySchemes:
    Authorization:
      type: http
      scheme: basic
